import type { PreparationFilingReadiness, PreparationRecord } from "@/domain/preparations";
import type { ExportFormat, JurisdictionCapability } from "@/domain/jurisdictions";

export const EXPORT_SCHEMA_VERSION = "1.0.0";

export interface ExportMetadata {
  readonly schemaVersion: typeof EXPORT_SCHEMA_VERSION;
  readonly preparationId: string;
  readonly jurisdiction: string;
  readonly jurisdictionCode: string;
  readonly taxYear: string;
  readonly registryVersion: string;
  readonly ruleProfileId: string;
  readonly ruleProfileVersion: string;
  readonly calculationLabel: PreparationRecord["calculationLabel"];
  readonly readiness: PreparationFilingReadiness;
  readonly source: string;
  readonly sourceVerifiedAt: string;
  readonly deadlineSource: string;
  readonly deadlineVerifiedAt: string;
  readonly generatedAt: string;
  readonly notSubmitted: true;
}

export interface ExportArtifact {
  readonly format: ExportFormat;
  readonly fileName: string;
  readonly mimeType: string;
  /** Generated bytes are returned to the caller; only artifactRef is persisted. */
  readonly data: Blob;
  readonly artifactRef: string;
}

export interface ExportPackage {
  readonly id: string;
  readonly preparationId: string;
  readonly schemaVersion: typeof EXPORT_SCHEMA_VERSION;
  readonly status: "exported";
  readonly metadata: ExportMetadata;
  readonly generatedAt: string;
  readonly artifacts: readonly ExportArtifact[];
}

export interface ExportContext {
  readonly preparation: PreparationRecord;
  readonly receipts: readonly import("@/domain/receipts").ReceiptRecord[];
  readonly capability: JurisdictionCapability;
  readonly metadata: ExportMetadata;
}
